name: identity
description: UI for Sunshine Identity Module.

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  path_provider: ^1.6.5
  flutter_screenutil: ^1.1.0
  injectable: ^0.3.0
  websafe_svg: ^1.1.0
  get_it: ^4.0.2
  shared_preferences: ">=0.5.0 <2.0.0"
  identity_client:
    path: ./packages/identity_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^0.3.5
  build_runner: ^1.9.0
flutter:
  uses-material-design: true
  assets:
    - assets/svg/
