[package]
name = "identity-client"
version = "0.1.0"
authors = ["Shady Khalifa <shekohex@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies.ffi]
version = "0.1.1"
package = "sunshine-identity-ffi"

[dependencies.sunshine-client]
git = "https://github.com/sunshine-protocol/sunshine.git"
package = "sunshine-client"
features = ["light"]
