name: identity_client
description: A new flutter plugin to the native identity module.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  ffi:
  isolate:
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: foundation.sunshine.identity_client
        pluginClass: IdentityClientPlugin
      ios:
        pluginClass: IdentityClientPlugin
